### ISSUE TITLE
LoRa and Sigfox dual stack

### ISSUE THREAD

**Issue by jpmeijers** [aureleq/muRataSigfox#1]
> Load both LoRa and Sigfox stacks on same module to switch between both technologies (coming next)

It would be great to see this happening. That would be the killer feature of the Murata module.

**Comment by ThomasUnivRennes1** [comment]
Hi @aureleq , 

Could you tell us more about : 

> Load both LoRa and Sigfox stacks on same module to switch between both technologies (coming next)

Thank's, Thomas.

**Comment by aureleq** [comment]
I have created a new repo for it, see here: https://github.com/aureleq/SigfoxLoRa_Murata
